2024-08-28 23:20:48,646 - ERROR - Error creating table: No section: 'database'
Traceback (most recent call last):
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\app.py", line 15, in main
    create_table()
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 16, in create_table
    db_path = get_db_path()
              ^^^^^^^^^^^^^
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 9, in get_db_path
    return config.get('database', 'db_path')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'database'
2024-08-28 23:20:48,652 - ERROR - Error creating table: No section: 'database'
Traceback (most recent call last):
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\app.py", line 15, in main
    create_table()
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 16, in create_table
    db_path = get_db_path()
              ^^^^^^^^^^^^^
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 9, in get_db_path
    return config.get('database', 'db_path')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'database'
2024-08-28 23:21:49,069 - ERROR - Error creating table: No section: 'database'
Traceback (most recent call last):
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\app.py", line 15, in main
    create_table()
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 16, in create_table
    db_path = get_db_path()
              ^^^^^^^^^^^^^
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 9, in get_db_path
    return config.get('database', 'db_path')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'database'
2024-08-28 23:21:51,296 - ERROR - Error creating table: No section: 'database'
Traceback (most recent call last):
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\app.py", line 15, in main
    create_table()
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 16, in create_table
    db_path = get_db_path()
              ^^^^^^^^^^^^^
  File "c:\Users\danic\Desktop\temp\py_with_ui_test\my_app\utils\db_helper.py", line 9, in get_db_path
    return config.get('database', 'db_path')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'database'
